language: python
sudo: required
dist: xenial

python:
  - "3.7"
  - "3.6"
  - "3.5"

matrix:
  fast_finish: true

install:
  - ROBOTPY_NO_DEPS=1 pip install -r travis-requirements.txt
script:
  - RUNCOVERAGE=1 wpilib/tests/run_tests.sh

jobs:
  include:
  - python: "3.5"
    # NOTE: keep this version in sync with readthedocs
    install:
    - pip install -r docs/requirements.txt
    script:
    - make -C docs html

  - stage: format-check
    python: "3.6"
    install:
    - pip install black
    script:
    - black --check --diff .

  - stage: deploy-pypi
    if: tag IS present
    env:
      - PACKAGE=hal-base
      - PACKAGE=wpilib
    install: skip
    script: cd $PACKAGE
    deploy:
    - provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      distributions: sdist bdist_wheel
      on:
        tags: true

  - if: tag IS present
    env:
      - PACKAGE=hal-sim
      - PACKAGE=hal-roborio
    install: skip
    script: cd $PACKAGE
    deploy:
    - provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      distributions: sdist
      on:
        tags: true

  - stage: deploy-github
    if: tag IS present
    install: skip
    script: devtools/build_installer.sh
    deploy:
    - provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      file_glob: true
      file: dist/robotpy-*.zip
      skip_cleanup: true
      on:
        tags: true

git:
  depth: 200
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
